### ISSUE TITLE
scheduling conflicting classes

### ISSUE THREAD

**Issue by Exr0n** [rchalamala/caltech.dev#5]
Hi, annoying freshman is back

On the new admit server:

![image](https://github.com/rchalamala/caltech.dev/assets/25516241/5ee20430-9f5e-436a-b4d7-205be8e11a22)

Need: I am apparently not the only person who gets confused when a conflict cases all the courses to disappear.
- is there a more clear way to show what's causing the conflict?
- imagine it just adds the courses in then highlights the overlap in red, both on the scheduler and the sidebar

Ideas to help:
- deduplicate schedules that have the same time blocks but are just different sections. Right now, if classes have many sections that meet at the same time (esp core classes) then the number of arrangements to click through explodes.
    - could we do this as a preprocessing step on the data?
- when classes conflict, show a few arrangements that have the least overlap, and highlight the overlap in red
- maybe convert day begin/end bounds into virtual classes so that we can show arrangements that would work if ppl are willing to have longer days
- maybe move the section selector dropdown into the collapsed view, so that you can see at a glance which courses have no section selected

What do yall think? Happy to implement these and make a pr if it sounds like a plan. Cc
@ericlovesmath @rchalamala @zack466 

Also I'm going on the caltech y camping trip thing so will have spotty cell. See yall on campus next week!

**Comment by ericlovesmath** [comment]
> Need: I am apparently not the only person who gets confused when a conflict cases all the courses to disappear.

The purpose of the lock button is the prevent the courses from switching out sections on conflicts. If there a conflicting course is added, then they get kicked out with no selected section (but still remain in the course listing). We can probably make that more clear.

Overlapping courses right now can be seen if you just select two sections that overlap; they pop up next to each other.

I think we might need to add some text based instructions, but not necessarily functional changes. Feel free to make changes if you want, but don't overexert yourself on your final fully free summer ^^;

Feel free to message me at @bunch_of_skittles on Discord if you want faster/more detailed responses ^^
