### ISSUE TITLE
Incorrect time for Ec 11

### ISSUE THREAD

**Issue by echthesia** [rchalamala/caltech.dev#8]
Ec 11 is erroneously listed in the course file as being TR 22:30 - 23:55.

**Comment by ericlovesmath** [comment]
[Fixed!](https://github.com/rchalamala/caltech.dev/commit/06adec5d4073929b467272e13d573edafb89a3c3) Thank you! Should be deployed now, you may need to delete Ec 11 and add it back for it to be reflected.
