### ISSUE TITLE
Crash on adding course ending after 23:00 to schedule

### ISSUE THREAD

**Issue by echthesia** [rchalamala/caltech.dev#9]
Adding a course with an end time after 23:00 (eg Ec 11 before #8 was fixed) causes the app to crash. If I'm reading planner.tsx right, this is because it attempts to set the maximum of the planner to 24:00 which is interpreted as 0:00 on the next day. Admittedly this isn't especially important because no real class will ever run that late.

**Comment by ericlovesmath** [comment]
Fixed in (#8)[https://github.com/rchalamala/caltech.dev/issues/8], you're right, but if Caltech starts hosting classes that span from 11pm to 1am, I think we have bigger problems ^^;

Will fix if this actually becomes a problem, but I doubt it.
